# Generated by Django 4.2.14 on 2024-07-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_donation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject'), ('Volunteer Allocated', 'Volunteer Allocated'), ('Volunteer Not Allocated', 'Volunteer Not Allocated'), ('Donation Received', 'Donation Received'), ('Donation Not Received', 'Donation Not Received'), ('Delievered Successfully', 'Delievered Successfully')], default='Pending', max_length=50),
        ),
    ]
