# Generated by Django 4.2.30 on 2026-07-21 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_donation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-donationdate']},
        ),
        migrations.AlterModelOptions(
            name='donationarea',
            options={'ordering': ['areaname']},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['-regdate']},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-creationdate'], 'verbose_name_plural': 'Gallery items'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['-regdate']},
        ),
        migrations.AlterField(
            model_name='donation',
            name='adminremark',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='collectionAddress',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='app.donationarea'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationname',
            field=models.CharField(choices=[('Food Donation', 'Food Donation'), ('Cloth Donation', 'Cloth Donation'), ('Shoes Donation', 'Shoes Donation'), ('Books Donation', 'Books Donation'), ('Furniture Donation', 'Furniture Donation'), ('Home Donate', 'Home Donate'), ('Frig Donation', 'Fridge Donation'), ('Byc Donation', 'Bicycle Donation'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='app.donor'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject'), ('Volunteer Allocated', 'Volunteer Allocated'), ('Volunteer Not Allocated', 'Volunteer Not Allocated'), ('Donation Received', 'Donation Received'), ('Donation Not Received', 'Donation Not Received'), ('Donation Delivered Successfully', 'Donation Delivered Successfully')], db_index=True, default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='updationdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_donations', to='app.volunteer'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='volunteerremark',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='deliverypic',
            field=models.FileField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='app.donation'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='aboutme',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='adminremark',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='updationdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'donationdate'], name='app_donatio_status_c1a131_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', 'status'], name='app_donatio_donor_i_e91d94_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['volunteer', 'status'], name='app_donatio_volunte_df83c3_idx'),
        ),
    ]
